-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- TASKS TABLE
create table public.tasks (
  id bigint generated by default as identity primary key,
  text text not null,
  completed boolean default false,
  date timestamp with time zone default now(),
  created_at timestamp with time zone default now(),
  is_recurring boolean default false,
  user_id text -- Optional: to track who created it if we add auth later
);

-- SHOPPING LIST TABLE
create table public.shopping_items (
  id bigint generated by default as identity primary key,
  text text not null,
  completed boolean default false,
  created_at timestamp with time zone default now()
);

-- RECURRING TASKS TABLE
create table public.recurring_tasks (
  id bigint generated by default as identity primary key,
  text text not null,
  frequency text not null check (frequency in ('daily', 'weekly')),
  days integer[] default '{}', -- Array of integers 0-6 (Sunday-Saturday)
  created_at timestamp with time zone default now()
);

-- RLS POLICIES (Simple Public Access for "Family" usage for now)
alter table public.tasks enable row level security;
alter table public.shopping_items enable row level security;
alter table public.recurring_tasks enable row level security;

-- Policy: Allow full access to anon users (since it's a private family app URL)
-- NOTE: In production, consider adding at least a shared API key check or basic auth if exposed.
create policy "Allow generic access" on public.tasks for all using (true) with check (true);
create policy "Allow generic access" on public.shopping_items for all using (true) with check (true);
create policy "Allow generic access" on public.recurring_tasks for all using (true) with check (true);
